"use client";

import { useMemo, useState } from "react";
import { useDebounce } from "use-debounce";
import { Alert, Box } from "@mui/material";

import PageHeader from "@/components/common/PageHeader";
import SearchBar from "@/components/common/SearchBar";
import DataTable from "@/components/common/DataTable";
import Loading from "@/components/common/Loading";

import { incentiveColumns } from "@/components/columns/incentives";

import { useIncentives } from "@/hooks/useIncentive";
import useSocketRefresh from "@/hooks/useSocketRefresh";

export default function IncentivesPage() {
  const [page, setPage] = useState(1);
  const [limit, setLimit] = useState(10);

  const [search, setSearch] = useState("");
  const [debouncedSearch] = useDebounce(search, 500);

  const { data, isLoading, isFetching, error } = useIncentives({
    page,
    limit,
    searchText: debouncedSearch,
  });

  useSocketRefresh({
    queryKey: ["incentive"],
  });

  const rows = useMemo(() => {
    return data?.data ?? [];
  }, [data]);

  if (error) {
    return (
      <Alert severity="error">
        Failed to load incentives.
      </Alert>
    );
  }

  return (
    <Box>
      <PageHeader
        title="Employee Incentives"
        subtitle="Total brokerage generated by each employee"
      />

      <SearchBar
        value={search}
        placeholder="Search employee by name or code..."
        onChange={setSearch}
      />

      {(isLoading && !data) ? (
        <Loading />
      ) : (
        <DataTable
          rows={rows.data}
          columns={incentiveColumns}
          loading={isFetching}
          pagination={{
            page: rows?.pagination?.page ?? 1,
            limit: rows?.pagination?.limit ?? 10,
            total: rows?.pagination?.total ?? 0,
          }}
          onPaginationChange={(page, limit) => {
            setPage(page);
            setLimit(limit);
          }}
        />
      )}
    </Box>
  );
}